# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecms_app', '0001_initial'),
        ('ecms_course_create_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifycoursestart',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecms_course_create_app.Course'),
        ),
    ]
