# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import library_app.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils_app', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='non', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('filename', models.FileField(max_length=2000, null=True, upload_to=library_app.models.upload_library_book)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.Language')),
            ],
            options={
                'db_table': 'lib_books',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='LibSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'lib_subject',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='libbook',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.LibSubject'),
        ),
        migrations.AddField(
            model_name='libbook',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
