# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecms_course_create_app.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('utils_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.CharField(max_length=200)),
                ('effort', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_author', models.CharField(max_length=200)),
                ('fees', models.FloatField(default=0.0)),
                ('syllabus_file', models.FileField(max_length=2000, null=True, upload_to=ecms_course_create_app.models.upload_course_syllabus)),
                ('photo_file', models.ImageField(max_length=2000, null=True, upload_to=ecms_course_create_app.models.upload_course_img)),
                ('photo_file_name', models.CharField(max_length=200)),
                ('delivery_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.DeliveryMode')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.Language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.Level')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('title',),
                'db_table': 'subject',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecms_course_create_app.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_subs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.SubtitlesLanguage'),
        ),
    ]
