# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecms_course_create_app.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils_app', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.CharField(max_length=200)),
                ('effort', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_author', models.CharField(max_length=200)),
                ('fees', models.FloatField(default=0.0)),
                ('syllabus_file', models.FileField(max_length=2000, null=True, upload_to=ecms_course_create_app.models.upload_course_syllabus)),
                ('photo_file', models.ImageField(max_length=2000, null=True, upload_to=ecms_course_create_app.models.upload_course_img)),
                ('photo_file_name', models.CharField(max_length=200)),
                ('delivery_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.DeliveryMode')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.Language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.Level')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='non', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('order_id', models.IntegerField()),
                ('text_content', models.TextField()),
                ('meta_description', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='ecms_course_create_app.Course')),
            ],
            options={
                'db_table': 'lesson',
                'ordering': ('order_id',),
            },
        ),
        migrations.CreateModel(
            name='LessonImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('file', models.ImageField(blank=True, max_length=2000, null=True, upload_to=ecms_course_create_app.models.upload_lesson_img)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_file_imgs', to='ecms_course_create_app.Lesson')),
            ],
            options={
                'db_table': 'lesson_file_imgs',
            },
        ),
        migrations.CreateModel(
            name='LessonQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('quiz_id', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_module_lesson_quizes', to='ecms_course_create_app.Course')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quizes', to='ecms_course_create_app.Lesson')),
            ],
            options={
                'db_table': 'lesson_quizes',
                'verbose_name_plural': 'Lesson Quizes',
                'ordering': ['quiz_id'],
                'verbose_name': 'Lesson Quiz',
            },
        ),
        migrations.CreateModel(
            name='LessonQuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('choices', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('question', models.TextField()),
                ('explanation', models.TextField(null=True)),
                ('correct_answer', models.CharField(max_length=500)),
                ('qtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.QuestionType')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_questions', to='ecms_course_create_app.LessonQuiz')),
            ],
            options={
                'db_table': 'lesson_quiz_questions',
                'verbose_name_plural': 'Lesson Quiz Questions',
                'verbose_name': 'Lesson Quiz Question',
            },
        ),
        migrations.CreateModel(
            name='LessonQuizQuestionImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('file', models.ImageField(blank=True, max_length=2000, null=True, upload_to=ecms_course_create_app.models.upload_lesson_img)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_question_file_imgs', to='ecms_course_create_app.LessonQuizQuestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecms_course_create_app.LessonQuiz')),
            ],
            options={
                'db_table': 'lesson_quiz_question_file_imgs',
                'verbose_name': 'Lesson Quiz Question Image',
            },
        ),
        migrations.CreateModel(
            name='LessonQuizQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('context', models.CharField(max_length=500)),
                ('order_id', models.IntegerField()),
                ('lesson_quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_question_options', to='ecms_course_create_app.LessonQuizQuestion')),
            ],
            options={
                'db_table': 'lesson_quiz_question_options',
                'verbose_name_plural': 'Lesson Quiz Questions Options',
                'ordering': ('order_id',),
                'verbose_name': 'Lesson Quiz Question Option',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='non', max_length=200)),
                ('overview', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('order_id', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='ecms_course_create_app.Course')),
            ],
            options={
                'db_table': 'module',
                'ordering': ('order_id',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'subject',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_lesson_quizes', to='ecms_course_create_app.Module'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_lessons', to='ecms_course_create_app.Module'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecms_course_create_app.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_subs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.SubtitlesLanguage'),
        ),
    ]
